
development:
  adapter: postgresql
  encoding: unicode
  database: depot_development
  pool: 5
  username: phipn
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: depot_test
  pool: 5
  username: phipn
  password: 123456